<!-- CONTENT STARTS -->
<div id="content1">
	<!-- FLASH HEAD -->
	<div id="flash_div" class="ie_layout" style="padding-top:14px;">
		<div style="background-color:#000;z-index:10000;position:absolute;top:0;left:0;height:14px;width:560px;"></div>
		<div id="flash_placeholder" style="width:560px;height:305px;overflow:hidden;position:relative;">
		#IMAGE#
		</div>
		<div class="menu_above_flash">
			<div class="menu_above_flash_inner blackbar_added">
			#BLACKBAR#
			</div>
		</div>
	</div>
	<!-- ////////// -->
	<div>
		<table cellspacing="0" cellpadding="0" border="0" class="table_content">
			<tr>
				<td valign="top" class="td_left">
					<div class="div_left8">
			<h1 style="font-size:27px;">#TITLE#</h1>
			<!-- BODY TEXT STARTS -->
			#BODY#
			<!-- BODY TEXT ENDS -->
			</div>
				</td>
				<td valign="top" class="td_right">
			<!-- PUSHDOWNSTARTS -->
					<div class="div_right8">
					<div style="font-weight:bold;font-size:17px;color:#777;">FEATURED LINKS</div>
					#FEATUREDLINKS#
					</div>
			<!-- PUSHDOWNENDS -->
				</td>
			</tr>
		</table>
	</div>
</div>
<!-- CONTENT ENDS -->
