<!-- captured from www-dev 2026-09-15; closes the wrapper opened in header.inc -->
<footer data-tw-theme="neutral-900" class="relative">
   <div class="bg-theme-bg-color text-theme-text-color py-vertical-space-padding">
      <div class="container">
         <div class="flex flex-col gap-10">
            <div class="flex flex-col gap-y-6 md:flex-row md:flex-wrap gap-x-12 justify-between md:items-center">
               <div class=" flex flex-col gap-4 grow lg:flex-row lg:flex-wrap lg:items-center lg:gap-12 xl:gap-16 "><a href="https://www.wichita.edu" aria-label="WSU logo" class="grow relative aspect-[322/73] max-w-[calc(322rem/16)]"><img alt="" src="/_resources/_theme/images/site-logo.svg" class="absolute inset-0 size-full object-contain"></a><address class="not-italic flex flex-col gap-2 text-[calc(13rem/16)]/[1.1] text-white lg:pl-4 lg:border-l border-yellow">
                     <div>1845 Fairmount St., Wichita, Kansas, 67260</div>
                     <div class="flex flex-wrap gap-x-3 gap-y-1">
                        <div class="pr-3 relative after:absolute after:bg-current after:w-px after:h-4 after:right-0 after:top-1/2 after:-translate-y-1/2"><a href="tel:+013169783456" class="underline font-medium hocus:text-yellow"><span class="sr-only">Phone: </span>(316) 978-3456</a></div>
                        <div><a href="mailto:operator@wichita.edu?subject=Contact%20Wichita%20State" class="underline font-medium hocus:text-yellow">Email Us</a></div>
                     </div>
                  </address>
               </div>
               <div>
                  <div class="space-y-2.5">
                     <ul role="list" class="flex flex-wrap gap-5">
                        <li class="relative size-8"><a class="absolute inset-0 group/social-link" href="https://facebook.com/wichita.state/" aria-label="Facebook"><span aria-hidden="true" class="absolute inset-0 mask-custom mask-contain transition-colors bg-theme-social-link-color group-hocus/social-link:bg-theme-social-link-hocus-color" style="--tw-mask-image: url('https://www-dev.wichita.edu/_resources/_theme/images/social-icons/facebook.svg');"></span></a></li>
                        <li class="relative size-8"><a class="absolute inset-0 group/social-link" href="https://x.com/wichitastate/" aria-label="X (Twitter)"><span aria-hidden="true" class="absolute inset-0 mask-custom mask-contain transition-colors bg-theme-social-link-color group-hocus/social-link:bg-theme-social-link-hocus-color" style="--tw-mask-image: url('https://www-dev.wichita.edu/_resources/_theme/images/social-icons/x.svg');"></span></a></li>
                        <li class="relative size-8"><a class="absolute inset-0 group/social-link" href="https://instagram.com/wichitastateu/" aria-label="Instagram"><span aria-hidden="true" class="absolute inset-0 mask-custom mask-contain transition-colors bg-theme-social-link-color group-hocus/social-link:bg-theme-social-link-hocus-color" style="--tw-mask-image: url('https://www-dev.wichita.edu/_resources/_theme/images/social-icons/instagram.svg');"></span></a></li>
                        <li class="relative size-8"><a class="absolute inset-0 group/social-link" href="https://wsu.news/Youtube" aria-label="YouTube"><span aria-hidden="true" class="absolute inset-0 mask-custom mask-contain transition-colors bg-theme-social-link-color group-hocus/social-link:bg-theme-social-link-hocus-color" style="--tw-mask-image: url('https://www-dev.wichita.edu/_resources/_theme/images/social-icons/youtube.svg');"></span></a></li>
                        <li class="relative size-8"><a class="absolute inset-0 group/social-link" href="https://linkedin.com/school/wichita-state-university" aria-label="LinkedIn"><span aria-hidden="true" class="absolute inset-0 mask-custom mask-contain transition-colors bg-theme-social-link-color group-hocus/social-link:bg-theme-social-link-hocus-color" style="--tw-mask-image: url('https://www-dev.wichita.edu/_resources/_theme/images/social-icons/linkedin.svg');"></span></a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="flex flex-wrap lg:flex-nowrap gap-x-12 justify-between gap-y-10 border-t border-dashed border-neutral-400 pt-10">
               <div class="flex flex-col gap-6 lg:min-w-[40%]">
                  <ul role="list" class="flex flex-wrap gap-4">
                     <li><a href="#" class="inline-block text-center font-bold text-base/none px-4 py-3 bg-neutral-500 text-white hocus:bg-yellow hocus:text-neutral-800">Request Info</a></li>
                     <li><a href="#" class="inline-block text-center font-bold text-base/none px-4 py-3 bg-neutral-500 text-white hocus:bg-yellow hocus:text-neutral-800">Visit</a></li>
                     <li><a href="#" class="inline-block text-center font-bold text-base/none px-4 py-3 bg-neutral-500 text-white hocus:bg-yellow hocus:text-neutral-800">Apply</a></li>
                  </ul>
                  <div>
                     <ul role="list" class="nc-icon-link-list flex flex-wrap gap-y-3 gap-x-8 flex-row">
                        <li><span class="nc-icon-link-wrapper" style="--tw-mask-image: url('/_resources/_theme/images/map-pin.svg');"><a class="nc-icon-link" href="https://www.youvisit.com/tour/wichita/wichitastate"><span class="nc-icon-link__text">Virtual Tour</span></a><span class="nc-icon-link__icon" aria-hidden="true"></span></span></li>
                        <li><span class="nc-icon-link-wrapper" style="--tw-mask-image: url('/_resources/_theme/images/map.svg');"><a class="nc-icon-link" href="https://wichita.edu/about/maps_directions.php"><span class="nc-icon-link__text">Campus Map and Directions</span></a><span class="nc-icon-link__icon" aria-hidden="true"></span></span></li>
                     </ul>
                  </div>
               </div>
               <ul role="list" class="flex flex-wrap gap-y-4 gap-x-8 lg:shrink descendants:w-max">
                  <li><a aria-label="Wichita State University Foundation and Alumni Engagement" href="#" class="block">
                        <div aria-hidden="true" class="[&amp;_img]:w-auto [&amp;_img]:h-9"><picture><img xmlns:ouc="http://omniupdate.com/XSL/Variables" src="/_resources/_theme/images/wsufae.svg" role="presentation" alt=""></picture></div></a></li>
                  <li><a aria-label="Shocker Store" href="#" class="block">
                        <div aria-hidden="true" class="[&amp;_img]:w-auto [&amp;_img]:h-9"><picture><img xmlns:ouc="http://omniupdate.com/XSL/Variables" src="/_resources/_theme/images/shocker-store.svg" role="presentation" alt=""></picture></div></a></li>
                  <li><a aria-label="Age-Friendly University Global Network" href="#" class="block">
                        <div aria-hidden="true" class="[&amp;_img]:w-auto [&amp;_img]:h-9"><picture><img xmlns:ouc="http://omniupdate.com/XSL/Variables" src="/_resources/_theme/images/age-friendly-university-global-network.svg" role="presentation" alt=""></picture></div></a></li>
               </ul>
            </div>
            <div class=" flex flex-wrap gap-x-12 justify-between gap-y-8 border-t border-dashed border-neutral-400 pt-10 lg:flex-nowrap lg:gap-x-24 xl:gap-x-48 ">
               <div class="flex flex-col gap-6">
                  <ul role="list" class="text-xs flex flex-wrap gap-x-2 gap-y-1.5 text-white font-medium">
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/directories/directory-a-z.php" class="hocus:text-yellow">A-Z&nbsp;Index</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="https://jobs.wichita.edu" class="hocus:text-yellow">Careers and Employment</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/about/free_expression/index.php" class="hocus:text-yellow">Freedom&nbsp;of&nbsp;Expression</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/about/policy/index.php" class="hocus:text-yellow">Policies&nbsp;and&nbsp;Procedures</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/about/privacy.php" class="hocus:text-yellow">Privacy&nbsp;Policy</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/about/policy/ch_03/ch3_02.php" class="hocus:text-yellow">Notice&nbsp;of&nbsp;Nondiscrimination</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/administration/oiec/titleixstatement.php" class="hocus:text-yellow">Title&nbsp;IX</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/services/emergency/index.php" class="hocus:text-yellow">Campus&nbsp;Safety</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/services/mrc/access/index.php" class="hocus:text-yellow">Accessibility</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/about/public_information/index.php" class="hocus:text-yellow">Public&nbsp;Information</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="https://learn.wichita.edu/" class="hocus:text-yellow">Website&nbsp;Support</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/about/free_expression/kbor_foe_statement.php" class="hocus:text-yellow">KBOR Freedom of Expression Statement</a></li>
                     <li class="relative pr-3 after:relative after:inline-block last:pr-0 last:after:tw-hidden after:bg-current after:w-px after:-ml-px after:h-3 after:-right-2.5 after:top-[calc(1rem/16)]"><a href="/academics/academic_affairs/hlc/index.php" class="hocus:text-yellow">HLC Accreditation</a></li>
                  </ul><small class="block text-[calc(10rem/16)]/normal text-white"><span id="directedit">© </span>2026 Wichita State University. &nbsp; Wichita State University (“WSU”) does not discriminate on the basis of sex in its
                     education programs, activities, admissions and employment.</small></div>
               <div class="grow shrink-0 max-w-[calc(172rem/16)]"><a href="https://ksdegreestats.org/" aria-label="Degree Stats Logo" class="block">
                     <div aria-hidden="true"><img src="/_resources/_theme/images/kansas-degree-stats.svg" alt="" role="presentation"></div></a></div>
            </div>
         </div>
      </div>
   </div>
</footer><!--OU Search Ignore Start Here--></div>
      
<script async src="https://static.addtoany.com/menu/page.js"></script>
<script src="/_resources/js/direct-edit.js" defer></script>
