<!-- captured from https://www-dev.wichita.edu/academics/index.php on 2026-09-15; opens the min-h-screen wrapper that footer.inc closes -->
<!--OU Search Ignore Start Here-->
      <div class="flex flex-col min-h-screen">
         <div class="container"><a href="#main" class="bg-black text-white sr-only focus:not-sr-only focus:absolute focus:px-2 focus:py-1 focus:border focus:rounded-sm z-50">Skip to main content</a></div>
         <header id="site-header">
   <h2 class="sr-only">Wichita State University</h2>
   <div class="tw-hidden lg:block bg-neutral-800 text-neutral-200">
      <div class="container">
         <div class="flex justify-end items-center gap-6">
            <nav aria-label="Utility Navigation" class="">
               <ul role="list" class="flex flex-wrap gap-x-6 xl:gap-x-8 gap-y-2">
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="#">Leadership</a></li>
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="#">Innovation at WSU</a></li>
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="#">Research</a></li>
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="/directories">Directories</a></li>
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="#">Give to WSU</a></li>
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="https://myWSU.wichita.edu">myWSU</a></li>
                  <li><a class="text-neutral-300 hocus:text-yellow font-medium text-base/none" href="/onestop">OneStop</a></li>
               </ul>
            </nav>
            <div class="shrink-0 flex"><button data-main-menu-opener="true" aria-label="Main Menu" aria-controls="main-menu-modal" aria-haspopup="dialog" type="button" class="no-js-hidden relative w-[calc(53rem/16)] md-xs:w-[calc(64rem/16)] h-[calc(36rem/16)] bg-neutral-500 hocus:bg-neutral-600 transition-colors"><span aria-hidden="true" class="absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 mask-menu-button mask-contain bg-white w-[calc(37rem/16)] h-[calc(18rem/16)] will-change-transform"></span></button><div class="tw-hidden md-xs:block min-h-9"><a class="bg-yellow h-full flex items-center px-3 text-neutral-800 hocus:bg-neutral-200 uppercase font-black text-base/none" href="/apply">Apply Now</a></div>
            </div>
         </div>
      </div>
   </div>
   <div data-tw-theme="neutral-700" class="relative">
      <div class="bg-theme-bg-color text-theme-text-color py-3 xs:py-5">
         <div class="container">
            <div class=" flex flex-wrap justify-between items-center gap-4 xs:gap-8 lg:flex-nowrap lg:gap-8 "><a href="/" aria-label="Home" class=" shrink-0 grow relative aspect-[322/73] min-w-[calc(140rem/16)] max-w-[calc(228rem/16)] sm:max-w-[calc(280rem/16)] lg:min-w-[calc(280rem/16)] lg:max-w-[calc(322rem/16)] "><img alt="" src="/_resources/_theme/images/site-logo.svg" class="absolute inset-0 size-full object-contain"></a><div class="tw-hidden lg:block no-js-hidden">
                  <nav aria-label="Main">
                     <ol role="list" class="group/ol flex flex-wrap gap-x-6 xl:gap-x-8 gap-y-2 mt-1">
                        <li><button type="button" data-megamenu-toggler="true" aria-controls="main-nav-panel-2" aria-expanded="false" class=" peer uppercase font-semibold text-lg/none xl:text-xl/none text-neutral-300 hocus:text-yellow transition-colors group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:text-neutral-400 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:hocus:text-neutral-300 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:text-neutral-100 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:hocus:text-neutral-100 pb-1 border-b-4 border-transparent aria-expanded:border-yellow ">Academics</button><div id="main-nav-panel-2" role="group" aria-label="Academics" class=" tw-hidden lg:block absolute z-50 left-0 right-0 top-full invisible opacity-0 peer-aria-expanded:visible peer-aria-expanded:opacity-100 motion-safe:transition-[opacity,visibility] ">
                              <div data-tw-theme="neutral-700">
                                 <div class="bg-theme-bg-color bg-gradient-to-t from-[#232323] text-white pb-8 xl:pb-12">
                                    <div class="container">
                                       <ol role="list" class="flex justify-between gap-4 xl:gap-[calc(18rem/16)] leading-none">
                                          <li class=" featured [--w:calc(230rem/16)] [--pr:calc(20rem/16)] xl:[--pr:calc(64rem/16)] [--big-w:calc(var(--w)+var(--pr))] min-w-[--w] max-w-[--w] shrink-0 pt-2.5 has-[+:not(.featured)]:min-w-[--big-w] has-[+:not(.featured)]:max-w-[--big-w] has-[+:not(.featured)]:pr-[--pr] ">
                                             <div class="group/card-wrapper relative h-full">
                                                <div class=" flex flex-col gap-5 h-full bg-neutral-900 group-hover/card-wrapper:bg-neutral-700 border-t-4 border-yellow group-hover/card-wrapper:border-white translate-y-0 group-hover/card-wrapper:-translate-y-2 transition will-change-transform ">
                                                   <div class="flex flex-col gap-2 px-4 pb-4">
                                                      <h3><a href="#" class="text-base/tight font-bold focus-visible:text-yellow after:absolute after:inset-0 group-hover/card-wrapper:after:-inset-y-2">Majors and Programs</a></h3>
                                                      <div>
                                                         <div class="prose prose-sm max-w-4xl">Start your WSU journey by exploring our manyprograms of study.</div>
                                                      </div>
                                                   </div>
                                                   <div class="order-first [&amp;_img]:aspect-[3/2] [&amp;_img]:object-cover [&amp;_img]:w-full"><img xmlns:ouc="http://omniupdate.com/XSL/Variables" role="presentation" src="https://placehold.co/300x200" alt="" width="300" height="200"></div>
                                                </div>
                                             </div>
                                          </li>
                                          <li class=" featured [--w:calc(230rem/16)] [--pr:calc(20rem/16)] xl:[--pr:calc(64rem/16)] [--big-w:calc(var(--w)+var(--pr))] min-w-[--w] max-w-[--w] shrink-0 pt-2.5 has-[+:not(.featured)]:min-w-[--big-w] has-[+:not(.featured)]:max-w-[--big-w] has-[+:not(.featured)]:pr-[--pr] ">
                                             <div class="group/card-wrapper relative h-full">
                                                <div class=" flex flex-col gap-5 h-full bg-neutral-900 group-hover/card-wrapper:bg-neutral-700 border-t-4 border-yellow group-hover/card-wrapper:border-white translate-y-0 group-hover/card-wrapper:-translate-y-2 transition will-change-transform ">
                                                   <div class="flex flex-col gap-2 px-4 pb-4">
                                                      <h3><a href="#" class="text-base/tight font-bold focus-visible:text-yellow after:absolute after:inset-0 group-hover/card-wrapper:after:-inset-y-2">Applied Learning</a></h3>
                                                      <div>
                                                         <div class="prose prose-sm max-w-4xl">
                                                            <p><span>Explore the cornerstone of a WSU education—the many ways to put what your learn into
                                                                  practice.</span></p>
                                                         </div>
                                                      </div>
                                                   </div>
                                                   <div class="order-first [&amp;_img]:aspect-[3/2] [&amp;_img]:object-cover [&amp;_img]:w-full"><img xmlns:ouc="http://omniupdate.com/XSL/Variables" role="presentation" src="https://placehold.co/300x200" alt="" width="300" height="200"></div>
                                                </div>
                                             </div>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Opportunities</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Undergraduate Programs of Study</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Graduate School</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Online and Adult Learning</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Workforce, Professional and Community Education</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Planning and Support</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Course catalogs</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Schedule of courses</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Advising</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Student success and persistence</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">University libraries</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Academic Affairs</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Life after WSU</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Shock Your Career</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Transcripts</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">WSU Distinguished Emeriti Retirees</a></li>
                                             </ol>
                                          </li>
                                       </ol>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li><button type="button" data-megamenu-toggler="true" aria-controls="main-nav-panel-3" aria-expanded="false" class=" peer uppercase font-semibold text-lg/none xl:text-xl/none text-neutral-300 hocus:text-yellow transition-colors group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:text-neutral-400 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:hocus:text-neutral-300 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:text-neutral-100 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:hocus:text-neutral-100 pb-1 border-b-4 border-transparent aria-expanded:border-yellow ">Admissions</button><div id="main-nav-panel-3" role="group" aria-label="Admissions" class=" tw-hidden lg:block absolute z-50 left-0 right-0 top-full invisible opacity-0 peer-aria-expanded:visible peer-aria-expanded:opacity-100 motion-safe:transition-[opacity,visibility] ">
                              <div data-tw-theme="neutral-700">
                                 <div class="bg-theme-bg-color bg-gradient-to-t from-[#232323] text-white pb-8 xl:pb-12">
                                    <div class="container">
                                       <ol role="list" class="flex justify-between gap-4 xl:gap-[calc(18rem/16)] leading-none">
                                          <li class=" featured [--w:calc(230rem/16)] [--pr:calc(20rem/16)] xl:[--pr:calc(64rem/16)] [--big-w:calc(var(--w)+var(--pr))] min-w-[--w] max-w-[--w] shrink-0 pt-2.5 has-[+:not(.featured)]:min-w-[--big-w] has-[+:not(.featured)]:max-w-[--big-w] has-[+:not(.featured)]:pr-[--pr] ">
                                             <div class="group/card-wrapper relative h-full">
                                                <div class=" flex flex-col gap-5 h-full bg-neutral-900 group-hover/card-wrapper:bg-neutral-700 border-t-4 border-yellow group-hover/card-wrapper:border-white translate-y-0 group-hover/card-wrapper:-translate-y-2 transition will-change-transform ">
                                                   <div class="flex flex-col gap-2 px-4 pb-4">
                                                      <h3><a href="#" class="text-base/tight font-bold focus-visible:text-yellow after:absolute after:inset-0 group-hover/card-wrapper:after:-inset-y-2">One Featured Link</a></h3>
                                                      <div>
                                                         <div class="prose prose-sm max-w-4xl"><span>Explore the cornerstone of a WSU education—the many ways to put what your learn into
                                                               practice.</span></div>
                                                      </div>
                                                   </div>
                                                   <div class="order-first [&amp;_img]:aspect-[3/2] [&amp;_img]:object-cover [&amp;_img]:w-full"><img xmlns:ouc="http://omniupdate.com/XSL/Variables" role="presentation" src="https://placehold.co/300x200" alt="" width="300" height="200"></div>
                                                </div>
                                             </div>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Opportunities</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Undergraduate Programs of Study</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Graduate School</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Online and Adult Learning</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Workforce, Professional and Community Education</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Planning and Support</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Course catalogs</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Schedule of courses</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Advising</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Student success and persistence</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">University libraries</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Academic Affairs</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Life after WSU</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Shock Your Career</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Transcripts</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">WSU Distinguished Emeriti Retirees</a></li>
                                             </ol>
                                          </li>
                                       </ol>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li><button type="button" data-megamenu-toggler="true" aria-controls="main-nav-panel-4" aria-expanded="false" class=" peer uppercase font-semibold text-lg/none xl:text-xl/none text-neutral-300 hocus:text-yellow transition-colors group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:text-neutral-400 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:hocus:text-neutral-300 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:text-neutral-100 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:hocus:text-neutral-100 pb-1 border-b-4 border-transparent aria-expanded:border-yellow ">Student Life</button><div id="main-nav-panel-4" role="group" aria-label="Student Life" class=" tw-hidden lg:block absolute z-50 left-0 right-0 top-full invisible opacity-0 peer-aria-expanded:visible peer-aria-expanded:opacity-100 motion-safe:transition-[opacity,visibility] ">
                              <div data-tw-theme="neutral-700">
                                 <div class="bg-theme-bg-color bg-gradient-to-t from-[#232323] text-white pb-8 xl:pb-12">
                                    <div class="container">
                                       <ol role="list" class="flex justify-between gap-4 xl:gap-[calc(18rem/16)] leading-none">
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">No featued links in this one</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Undergraduate Programs of Study</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Graduate School</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Online and Adult Learning</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Workforce, Professional and Community Education</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Planning and Support</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Course catalogs</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Schedule of courses</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Advising</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Student success and persistence</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">University libraries</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Academic Affairs</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Life after WSU</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Shock Your Career</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Transcripts</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">WSU Distinguished Emeriti Retirees</a></li>
                                             </ol>
                                          </li>
                                       </ol>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li><button type="button" data-megamenu-toggler="true" aria-controls="main-nav-panel-5" aria-expanded="false" class=" peer uppercase font-semibold text-lg/none xl:text-xl/none text-neutral-300 hocus:text-yellow transition-colors group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:text-neutral-400 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:hocus:text-neutral-300 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:text-neutral-100 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:hocus:text-neutral-100 pb-1 border-b-4 border-transparent aria-expanded:border-yellow ">Athletics</button><div id="main-nav-panel-5" role="group" aria-label="Athletics" class=" tw-hidden lg:block absolute z-50 left-0 right-0 top-full invisible opacity-0 peer-aria-expanded:visible peer-aria-expanded:opacity-100 motion-safe:transition-[opacity,visibility] ">
                              <div data-tw-theme="neutral-700">
                                 <div class="bg-theme-bg-color bg-gradient-to-t from-[#232323] text-white pb-8 xl:pb-12">
                                    <div class="container">
                                       <ol role="list" class="flex justify-between gap-4 xl:gap-[calc(18rem/16)] leading-none">
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">No featured links again, but additional normal links</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Undergraduate Programs of Study</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Graduate School</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Online and Adult Learning</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Workforce, Professional and Community Education</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Planning and Support</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Course catalogs</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Schedule of courses</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Advising</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Student success and persistence</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">University libraries</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Academic Affairs</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Opportunities</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Undergraduate Programs of Study</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Graduate School</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Online and Adult Learning</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Workforce, Professional and Community Education</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Academic Planning and Support</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Course catalogs</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Schedule of courses</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Advising</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Student success and persistence</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">University libraries</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Academic Affairs</a></li>
                                             </ol>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Life after WSU</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Shock Your Career</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Transcripts</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">WSU Distinguished Emeriti Retirees</a></li>
                                             </ol>
                                          </li>
                                       </ol>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li><button type="button" data-megamenu-toggler="true" aria-controls="main-nav-panel-6" aria-expanded="false" class=" peer uppercase font-semibold text-lg/none xl:text-xl/none text-neutral-300 hocus:text-yellow transition-colors group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:text-neutral-400 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:hocus:text-neutral-300 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:text-neutral-100 group-has-[[data-megamenu-toggler][aria-expanded=true]]/ol:aria-expanded:hocus:text-neutral-100 pb-1 border-b-4 border-transparent aria-expanded:border-yellow ">About</button><div id="main-nav-panel-6" role="group" aria-label="About" class=" tw-hidden lg:block absolute z-50 left-0 right-0 top-full invisible opacity-0 peer-aria-expanded:visible peer-aria-expanded:opacity-100 motion-safe:transition-[opacity,visibility] ">
                              <div data-tw-theme="neutral-700">
                                 <div class="bg-theme-bg-color bg-gradient-to-t from-[#232323] text-white pb-8 xl:pb-12">
                                    <div class="container">
                                       <ol role="list" class="flex justify-between gap-4 xl:gap-[calc(18rem/16)] leading-none">
                                          <li class=" featured [--w:calc(230rem/16)] [--pr:calc(20rem/16)] xl:[--pr:calc(64rem/16)] [--big-w:calc(var(--w)+var(--pr))] min-w-[--w] max-w-[--w] shrink-0 pt-2.5 has-[+:not(.featured)]:min-w-[--big-w] has-[+:not(.featured)]:max-w-[--big-w] has-[+:not(.featured)]:pr-[--pr] ">
                                             <div class="group/card-wrapper relative h-full">
                                                <div class=" flex flex-col gap-5 h-full bg-neutral-900 group-hover/card-wrapper:bg-neutral-700 border-t-4 border-yellow group-hover/card-wrapper:border-white translate-y-0 group-hover/card-wrapper:-translate-y-2 transition will-change-transform ">
                                                   <div class="flex flex-col gap-2 px-4 pb-4">
                                                      <h3><a href="#" class="text-base/tight font-bold focus-visible:text-yellow after:absolute after:inset-0 group-hover/card-wrapper:after:-inset-y-2">Fewer Normal Links This Time</a></h3>
                                                      <div>
                                                         <div class="prose prose-sm max-w-4xl">Start your WSU journey by exploring our manyprograms of study.</div>
                                                      </div>
                                                   </div>
                                                   <div class="order-first [&amp;_img]:aspect-[3/2] [&amp;_img]:object-cover [&amp;_img]:w-full"><img xmlns:ouc="http://omniupdate.com/XSL/Variables" role="presentation" src="https://placehold.co/300x200" alt="" width="300" height="200"></div>
                                                </div>
                                             </div>
                                          </li>
                                          <li class=" featured [--w:calc(230rem/16)] [--pr:calc(20rem/16)] xl:[--pr:calc(64rem/16)] [--big-w:calc(var(--w)+var(--pr))] min-w-[--w] max-w-[--w] shrink-0 pt-2.5 has-[+:not(.featured)]:min-w-[--big-w] has-[+:not(.featured)]:max-w-[--big-w] has-[+:not(.featured)]:pr-[--pr] ">
                                             <div class="group/card-wrapper relative h-full">
                                                <div class=" flex flex-col gap-5 h-full bg-neutral-900 group-hover/card-wrapper:bg-neutral-700 border-t-4 border-yellow group-hover/card-wrapper:border-white translate-y-0 group-hover/card-wrapper:-translate-y-2 transition will-change-transform ">
                                                   <div class="flex flex-col gap-2 px-4 pb-4">
                                                      <h3><a href="#" class="text-base/tight font-bold focus-visible:text-yellow after:absolute after:inset-0 group-hover/card-wrapper:after:-inset-y-2">Applied Learning</a></h3>
                                                      <div>
                                                         <div class="prose prose-sm max-w-4xl">
                                                            <p><span>Explore the cornerstone of a WSU education—the many ways to put what your learn into
                                                                  practice.</span></p>
                                                         </div>
                                                      </div>
                                                   </div>
                                                   <div class="order-first [&amp;_img]:aspect-[3/2] [&amp;_img]:object-cover [&amp;_img]:w-full"><img xmlns:ouc="http://omniupdate.com/XSL/Variables" role="presentation" src="https://placehold.co/300x200" alt="" width="300" height="200"></div>
                                                </div>
                                             </div>
                                          </li>
                                          <li class="flex-1 flex flex-col gap-4 pr-2 xl:pr-6 last:pr-0 xl:last:pr-0">
                                             <h3><a href="#" class="font-bold text-base/tight hocus:text-yellow">Life after WSU</a></h3>
                                             <ol role="list" class="flex flex-col gap-3">
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Shock Your Career</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">Transcripts</a></li>
                                                <li><a href="#" class="text-sm/tight xl:text-[calc(15rem/16)]/tight hocus:text-yellow underline decoration-dotted decoration-transparent hocus:decoration-yellow decoration-1">WSU Distinguished Emeriti Retirees</a></li>
                                             </ol>
                                          </li>
                                       </ol>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                     </ol>
                  </nav>
               </div>
               <div class="no-js-hidden flex lg:tw-hidden"><button data-main-menu-opener="true" aria-label="Main Menu" aria-controls="main-menu-modal" aria-haspopup="dialog" type="button" class="no-js-hidden relative w-[calc(53rem/16)] md-xs:w-[calc(64rem/16)] h-[calc(36rem/16)] bg-neutral-500 hocus:bg-neutral-600 transition-colors"><span aria-hidden="true" class="absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 mask-menu-button mask-contain bg-white w-[calc(37rem/16)] h-[calc(18rem/16)] will-change-transform"></span></button><div class="tw-hidden md-xs:block min-h-9"><a class="bg-yellow h-full flex items-center px-3 text-neutral-800 hocus:bg-neutral-200 uppercase font-black text-base/none" href="/apply">Apply Now</a></div>
               </div>
            </div><noscript>
               <div class="mt-3">
                  <details class="pb-2">
                     <summary class="cursor-pointer max-w-max text-xl text-white hocus:text-yellow transition-colors">Main Menu</summary>
                     <div class="py-4">
                        <div class="grow flex flex-col" data-tw-theme="yellow">
                           <div class="relative grow bg-theme-bg-color text-theme-text-color h-full py-6">
                              <div id="modal-decorative-background" aria-hidden="true" class="absolute inset-0 after:absolute after:inset-0 after:bg-gradient-to-t after:from-yellow">
                                 <div aria-hidden="true" class="relative size-full overflow-hidden">
                                    <div data-bg-wheat="true" class="absolute inset-0 bg-[image:--wheat-tile] opacity-[--theme-wheat-opacity] [.simple-parallax-initialized&gt;&amp;]:bg-[length:--wheat-tile-parallax-size]" style="--wheat-tile: url('/_resources/_theme/images/wheat.svg'); --wheat-tile-width: 1440px; --wheat-tile-height: 1388px; --parallax-scale: 1.3; --wheat-tile-parallax-size: calc(var(--wheat-tile-width) / var(--parallax-scale)) calc(var(--wheat-tile-height) / var(--parallax-scale));"></div>
                                 </div>
                              </div>
                              <div class="container relative">
                                 <div class="flex flex-col gap-4">
                                    <div class="flex justify-end no-js-hidden"><button type="button" id="main-menu-closer" aria-label="Close modal" class="group/button relative size-10 -mr-2"><span aria-hidden="true" class="mask-x mask-contain bg-neutral-800 size-8 absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-1/2 group-hocus/button:bg-dark-red transition-colors"></span></button></div>
                                    <div class="flex flex-col gap-8 lg:gap-16">
                                       <form method="get" action="/search/" class=""><label for="searchField" class="sr-only">Search</label><div class="flex w-full h-[calc(60rem/16)] md:h-[calc(92rem/16)]"><input id="searchField" name="q" class="grow min-w-0 bg-white/80 px-3 border-b border-neutral-800 text-base md:text-2xl placeholder:text-neutral-400 md:px-8 md:border-b-2" placeholder="Search This Site"><button type="submit" class="shrink-0 bg-white/80 hocus:bg-white transition-colors px-3 font-bold border-b border-neutral-800 text-base md:text-xl md:px-8 md:border-b-2">Search</button></div>
                                       </form>
                                       <div class="flex flex-col gap-8 lg:flex-row lg:justify-between lg:gap-24 lg:[details_&amp;]:flex-col lg:[details_&amp;]:gap-12">
                                          <div class="lg:tw-hidden lg:[details_&amp;]:block">
                                             <nav aria-label="Main">
                                                <div xmlns:err="http://www.w3.org/2005/xqt-errors" data-accordion="true" data-variant="main-menu" data-close-others-on-open="true">
                                                   <div data-accordion-panel="true">
                                                      <h3 data-accordion-heading="true">Academics</h3>
                                                      <section data-accordion-section="true">
                                                         <div data-accordion-section-contents="true">
                                                            <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                               <li><a href="#">Majors and Programs</a></li>
                                                               <li><a href="#">Applied Learning</a></li>
                                                               <li><a href="#">Academic Opportunities</a><ol>
                                                                     <li><a href="#">Undergraduate Programs of Study</a></li>
                                                                     <li><a href="#">Graduate School</a></li>
                                                                     <li><a href="#">Online and Adult Learning</a></li>
                                                                     <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Academic Planning and Support</a><ol>
                                                                     <li><a href="#">Course catalogs</a></li>
                                                                     <li><a href="#">Schedule of courses</a></li>
                                                                     <li><a href="#">Advising</a></li>
                                                                     <li><a href="#">Student success and persistence</a></li>
                                                                     <li><a href="#">University libraries</a></li>
                                                                     <li><a href="#">Academic Affairs</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Life after WSU</a><ol>
                                                                     <li><a href="#">Shock Your Career</a></li>
                                                                     <li><a href="#">Transcripts</a></li>
                                                                     <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                                  </ol>
                                                               </li>
                                                            </ol>
                                                         </div>
                                                      </section>
                                                   </div>
                                                   <div data-accordion-panel="true">
                                                      <h3 data-accordion-heading="true">Admissions</h3>
                                                      <section data-accordion-section="true">
                                                         <div data-accordion-section-contents="true">
                                                            <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                               <li><a href="#">One Featured Link</a></li>
                                                               <li><a href="#">Academic Opportunities</a><ol>
                                                                     <li><a href="#">Undergraduate Programs of Study</a></li>
                                                                     <li><a href="#">Graduate School</a></li>
                                                                     <li><a href="#">Online and Adult Learning</a></li>
                                                                     <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Academic Planning and Support</a><ol>
                                                                     <li><a href="#">Course catalogs</a></li>
                                                                     <li><a href="#">Schedule of courses</a></li>
                                                                     <li><a href="#">Advising</a></li>
                                                                     <li><a href="#">Student success and persistence</a></li>
                                                                     <li><a href="#">University libraries</a></li>
                                                                     <li><a href="#">Academic Affairs</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Life after WSU</a><ol>
                                                                     <li><a href="#">Shock Your Career</a></li>
                                                                     <li><a href="#">Transcripts</a></li>
                                                                     <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                                  </ol>
                                                               </li>
                                                            </ol>
                                                         </div>
                                                      </section>
                                                   </div>
                                                   <div data-accordion-panel="true">
                                                      <h3 data-accordion-heading="true">Student Life</h3>
                                                      <section data-accordion-section="true">
                                                         <div data-accordion-section-contents="true">
                                                            <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                               <li><a href="#">No featued links in this one</a><ol>
                                                                     <li><a href="#">Undergraduate Programs of Study</a></li>
                                                                     <li><a href="#">Graduate School</a></li>
                                                                     <li><a href="#">Online and Adult Learning</a></li>
                                                                     <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Academic Planning and Support</a><ol>
                                                                     <li><a href="#">Course catalogs</a></li>
                                                                     <li><a href="#">Schedule of courses</a></li>
                                                                     <li><a href="#">Advising</a></li>
                                                                     <li><a href="#">Student success and persistence</a></li>
                                                                     <li><a href="#">University libraries</a></li>
                                                                     <li><a href="#">Academic Affairs</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Life after WSU</a><ol>
                                                                     <li><a href="#">Shock Your Career</a></li>
                                                                     <li><a href="#">Transcripts</a></li>
                                                                     <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                                  </ol>
                                                               </li>
                                                            </ol>
                                                         </div>
                                                      </section>
                                                   </div>
                                                   <div data-accordion-panel="true">
                                                      <h3 data-accordion-heading="true">Athletics</h3>
                                                      <section data-accordion-section="true">
                                                         <div data-accordion-section-contents="true">
                                                            <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                               <li><a href="#">No featured links again, but additional normal links</a><ol>
                                                                     <li><a href="#">Undergraduate Programs of Study</a></li>
                                                                     <li><a href="#">Graduate School</a></li>
                                                                     <li><a href="#">Online and Adult Learning</a></li>
                                                                     <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Academic Planning and Support</a><ol>
                                                                     <li><a href="#">Course catalogs</a></li>
                                                                     <li><a href="#">Schedule of courses</a></li>
                                                                     <li><a href="#">Advising</a></li>
                                                                     <li><a href="#">Student success and persistence</a></li>
                                                                     <li><a href="#">University libraries</a></li>
                                                                     <li><a href="#">Academic Affairs</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Academic Opportunities</a><ol>
                                                                     <li><a href="#">Undergraduate Programs of Study</a></li>
                                                                     <li><a href="#">Graduate School</a></li>
                                                                     <li><a href="#">Online and Adult Learning</a></li>
                                                                     <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Academic Planning and Support</a><ol>
                                                                     <li><a href="#">Course catalogs</a></li>
                                                                     <li><a href="#">Schedule of courses</a></li>
                                                                     <li><a href="#">Advising</a></li>
                                                                     <li><a href="#">Student success and persistence</a></li>
                                                                     <li><a href="#">University libraries</a></li>
                                                                     <li><a href="#">Academic Affairs</a></li>
                                                                  </ol>
                                                               </li>
                                                               <li><a href="#">Life after WSU</a><ol>
                                                                     <li><a href="#">Shock Your Career</a></li>
                                                                     <li><a href="#">Transcripts</a></li>
                                                                     <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                                  </ol>
                                                               </li>
                                                            </ol>
                                                         </div>
                                                      </section>
                                                   </div>
                                                   <div data-accordion-panel="true">
                                                      <h3 data-accordion-heading="true">About</h3>
                                                      <section data-accordion-section="true">
                                                         <div data-accordion-section-contents="true">
                                                            <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                               <li><a href="#">Fewer Normal Links This Time</a></li>
                                                               <li><a href="#">Applied Learning</a></li>
                                                               <li><a href="#">Life after WSU</a><ol>
                                                                     <li><a href="#">Shock Your Career</a></li>
                                                                     <li><a href="#">Transcripts</a></li>
                                                                     <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                                  </ol>
                                                               </li>
                                                            </ol>
                                                         </div>
                                                      </section>
                                                   </div>
                                                </div>
                                             </nav>
                                          </div>
                                          <div class="lg:order-last [&amp;_.nc-button]:w-full md-xs:[&amp;_.nc-button]:w-auto lg:[details_&amp;]:tw-hidden"><a class="nc-button" data-variant="1" href="/apply"><span class="nc-button-text">Apply Now</span></a></div>
                                          <div class="lg:tw-hidden border-t-5 border-dotted border-white pt-8">
                                             <nav aria-label="Utility Navigation" class="">
                                                <ul role="list" class="columns-[calc(160rem/16)] gap-6 descendants:break-inside-avoid children:pb-4 -mb-4 leading-none">
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Leadership</a></li>
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Innovation at WSU</a></li>
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Research</a></li>
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="/directories">Directories</a></li>
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Give to WSU</a></li>
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="https://myWSU.wichita.edu">myWSU</a></li>
                                                   <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="/onestop">OneStop</a></li>
                                                </ul>
                                             </nav>
                                          </div>
                                          <div class="border-t-5 border-dotted border-white pt-8 lg:border-t-0 lg:pt-0 lg:border-r-5 lg:pr-12 lg:grow lg:[details_&amp;]:border-r-0 lg:[details_&amp;]:pr-0 lg:[details_&amp;]:border-t-5 lg:[details_&amp;]:pt-12">
                                             <nav aria-label="Quick Links" class="">
                                                <ul role="list" class="columns-[calc(160rem/16)] gap-6 descendants:break-inside-avoid children:pb-4 -mb-4 leading-none lg:columns-2xs">
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Academic Calendar</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">A–Z Directory</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Blackboard</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Calendar of Events</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Office Hours</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Policies and Procedures</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Schedule of Courses</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Shocker Store</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Student Webmail</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Technology HelpDesk</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Transfer to WSU</a></li>
                                                   <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">University Libraries</a></li>
                                                </ul>
                                             </nav>
                                          </div>
                                       </div>
                                       <div class="tw-hidden lg:block mx-auto lg:[details_&amp;]:tw-hidden"><img width="677" height="564" alt="" src="/_resources/_theme/images/wushock.svg"></div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </details>
               </div></noscript></div>
      </div>
   </div>
   <div id="main-menu-modal" aria-hidden="true" class=" fixed z-[9999] inset-0 w-screen overflow-x-hidden overflow-y-auto overscroll-contain invisible [&amp;.is-open]:visible [&amp;.opening]:pointer-events-none [&amp;.closing]:pointer-events-none [--animation-duration:500ms] animate-[fade-in_var(--animation-duration)] aria-hidden:animate-[fade-out_var(--animation-duration)] ">
      <div role="dialog" aria-modal="true" aria-label="Main Menu" class="min-h-screen flex flex-col">
         <div class="grow flex flex-col" data-tw-theme="yellow">
            <div class="relative grow bg-theme-bg-color text-theme-text-color h-full py-6">
               <div id="modal-decorative-background" aria-hidden="true" class="absolute inset-0 after:absolute after:inset-0 after:bg-gradient-to-t after:from-yellow">
                  <div aria-hidden="true" class="relative size-full overflow-hidden">
                     <div data-bg-wheat="true" class="absolute inset-0 bg-[image:--wheat-tile] opacity-[--theme-wheat-opacity] [.simple-parallax-initialized&gt;&amp;]:bg-[length:--wheat-tile-parallax-size]" style="--wheat-tile: url('/_resources/_theme/images/wheat.svg'); --wheat-tile-width: 1440px; --wheat-tile-height: 1388px; --parallax-scale: 1.3; --wheat-tile-parallax-size: calc(var(--wheat-tile-width) / var(--parallax-scale)) calc(var(--wheat-tile-height) / var(--parallax-scale));"></div>
                  </div>
               </div>
               <div class="container relative">
                  <div class="flex flex-col gap-4">
                     <div class="flex justify-end no-js-hidden"><button type="button" id="main-menu-closer" aria-label="Close modal" class="group/button relative size-10 -mr-2"><span aria-hidden="true" class="mask-x mask-contain bg-neutral-800 size-8 absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-1/2 group-hocus/button:bg-dark-red transition-colors"></span></button></div>
                     <div class="flex flex-col gap-8 lg:gap-16">
                        <form method="get" action="/search/" class=""><label for="searchField" class="sr-only">Search</label><div class="flex w-full h-[calc(60rem/16)] md:h-[calc(92rem/16)]"><input id="searchField" name="q" class="grow min-w-0 bg-white/80 px-3 border-b border-neutral-800 text-base md:text-2xl placeholder:text-neutral-400 md:px-8 md:border-b-2" placeholder="Search This Site"><button type="submit" class="shrink-0 bg-white/80 hocus:bg-white transition-colors px-3 font-bold border-b border-neutral-800 text-base md:text-xl md:px-8 md:border-b-2">Search</button></div>
                        </form>
                        <div class="flex flex-col gap-8 lg:flex-row lg:justify-between lg:gap-24 lg:[details_&amp;]:flex-col lg:[details_&amp;]:gap-12">
                           <div class="lg:tw-hidden lg:[details_&amp;]:block">
                              <nav aria-label="Main">
                                 <div xmlns:err="http://www.w3.org/2005/xqt-errors" data-accordion="true" data-variant="main-menu" data-close-others-on-open="true">
                                    <div data-accordion-panel="true">
                                       <h3 data-accordion-heading="true">Academics</h3>
                                       <section data-accordion-section="true">
                                          <div data-accordion-section-contents="true">
                                             <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                <li><a href="#">Majors and Programs</a></li>
                                                <li><a href="#">Applied Learning</a></li>
                                                <li><a href="#">Academic Opportunities</a><ol>
                                                      <li><a href="#">Undergraduate Programs of Study</a></li>
                                                      <li><a href="#">Graduate School</a></li>
                                                      <li><a href="#">Online and Adult Learning</a></li>
                                                      <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Academic Planning and Support</a><ol>
                                                      <li><a href="#">Course catalogs</a></li>
                                                      <li><a href="#">Schedule of courses</a></li>
                                                      <li><a href="#">Advising</a></li>
                                                      <li><a href="#">Student success and persistence</a></li>
                                                      <li><a href="#">University libraries</a></li>
                                                      <li><a href="#">Academic Affairs</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Life after WSU</a><ol>
                                                      <li><a href="#">Shock Your Career</a></li>
                                                      <li><a href="#">Transcripts</a></li>
                                                      <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                   </ol>
                                                </li>
                                             </ol>
                                          </div>
                                       </section>
                                    </div>
                                    <div data-accordion-panel="true">
                                       <h3 data-accordion-heading="true">Admissions</h3>
                                       <section data-accordion-section="true">
                                          <div data-accordion-section-contents="true">
                                             <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                <li><a href="#">One Featured Link</a></li>
                                                <li><a href="#">Academic Opportunities</a><ol>
                                                      <li><a href="#">Undergraduate Programs of Study</a></li>
                                                      <li><a href="#">Graduate School</a></li>
                                                      <li><a href="#">Online and Adult Learning</a></li>
                                                      <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Academic Planning and Support</a><ol>
                                                      <li><a href="#">Course catalogs</a></li>
                                                      <li><a href="#">Schedule of courses</a></li>
                                                      <li><a href="#">Advising</a></li>
                                                      <li><a href="#">Student success and persistence</a></li>
                                                      <li><a href="#">University libraries</a></li>
                                                      <li><a href="#">Academic Affairs</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Life after WSU</a><ol>
                                                      <li><a href="#">Shock Your Career</a></li>
                                                      <li><a href="#">Transcripts</a></li>
                                                      <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                   </ol>
                                                </li>
                                             </ol>
                                          </div>
                                       </section>
                                    </div>
                                    <div data-accordion-panel="true">
                                       <h3 data-accordion-heading="true">Student Life</h3>
                                       <section data-accordion-section="true">
                                          <div data-accordion-section-contents="true">
                                             <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                <li><a href="#">No featued links in this one</a><ol>
                                                      <li><a href="#">Undergraduate Programs of Study</a></li>
                                                      <li><a href="#">Graduate School</a></li>
                                                      <li><a href="#">Online and Adult Learning</a></li>
                                                      <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Academic Planning and Support</a><ol>
                                                      <li><a href="#">Course catalogs</a></li>
                                                      <li><a href="#">Schedule of courses</a></li>
                                                      <li><a href="#">Advising</a></li>
                                                      <li><a href="#">Student success and persistence</a></li>
                                                      <li><a href="#">University libraries</a></li>
                                                      <li><a href="#">Academic Affairs</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Life after WSU</a><ol>
                                                      <li><a href="#">Shock Your Career</a></li>
                                                      <li><a href="#">Transcripts</a></li>
                                                      <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                   </ol>
                                                </li>
                                             </ol>
                                          </div>
                                       </section>
                                    </div>
                                    <div data-accordion-panel="true">
                                       <h3 data-accordion-heading="true">Athletics</h3>
                                       <section data-accordion-section="true">
                                          <div data-accordion-section-contents="true">
                                             <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                <li><a href="#">No featured links again, but additional normal links</a><ol>
                                                      <li><a href="#">Undergraduate Programs of Study</a></li>
                                                      <li><a href="#">Graduate School</a></li>
                                                      <li><a href="#">Online and Adult Learning</a></li>
                                                      <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Academic Planning and Support</a><ol>
                                                      <li><a href="#">Course catalogs</a></li>
                                                      <li><a href="#">Schedule of courses</a></li>
                                                      <li><a href="#">Advising</a></li>
                                                      <li><a href="#">Student success and persistence</a></li>
                                                      <li><a href="#">University libraries</a></li>
                                                      <li><a href="#">Academic Affairs</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Academic Opportunities</a><ol>
                                                      <li><a href="#">Undergraduate Programs of Study</a></li>
                                                      <li><a href="#">Graduate School</a></li>
                                                      <li><a href="#">Online and Adult Learning</a></li>
                                                      <li><a href="#">Workforce, Professional and Community Education</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Academic Planning and Support</a><ol>
                                                      <li><a href="#">Course catalogs</a></li>
                                                      <li><a href="#">Schedule of courses</a></li>
                                                      <li><a href="#">Advising</a></li>
                                                      <li><a href="#">Student success and persistence</a></li>
                                                      <li><a href="#">University libraries</a></li>
                                                      <li><a href="#">Academic Affairs</a></li>
                                                   </ol>
                                                </li>
                                                <li><a href="#">Life after WSU</a><ol>
                                                      <li><a href="#">Shock Your Career</a></li>
                                                      <li><a href="#">Transcripts</a></li>
                                                      <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                   </ol>
                                                </li>
                                             </ol>
                                          </div>
                                       </section>
                                    </div>
                                    <div data-accordion-panel="true">
                                       <h3 data-accordion-heading="true">About</h3>
                                       <section data-accordion-section="true">
                                          <div data-accordion-section-contents="true">
                                             <ol role="list" class="columns-2xs gap-12 descendants:break-inside-avoid children:pb-4 leading-none">
                                                <li><a href="#">Fewer Normal Links This Time</a></li>
                                                <li><a href="#">Applied Learning</a></li>
                                                <li><a href="#">Life after WSU</a><ol>
                                                      <li><a href="#">Shock Your Career</a></li>
                                                      <li><a href="#">Transcripts</a></li>
                                                      <li><a href="#">WSU Distinguished Emeriti Retirees</a></li>
                                                   </ol>
                                                </li>
                                             </ol>
                                          </div>
                                       </section>
                                    </div>
                                 </div>
                              </nav>
                           </div>
                           <div class="lg:order-last [&amp;_.nc-button]:w-full md-xs:[&amp;_.nc-button]:w-auto lg:[details_&amp;]:tw-hidden"><a class="nc-button" data-variant="1" href="/apply"><span class="nc-button-text">Apply Now</span></a></div>
                           <div class="lg:tw-hidden border-t-5 border-dotted border-white pt-8">
                              <nav aria-label="Utility Navigation" class="">
                                 <ul role="list" class="columns-[calc(160rem/16)] gap-6 descendants:break-inside-avoid children:pb-4 -mb-4 leading-none">
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Leadership</a></li>
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Innovation at WSU</a></li>
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Research</a></li>
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="/directories">Directories</a></li>
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="#">Give to WSU</a></li>
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="https://myWSU.wichita.edu">myWSU</a></li>
                                    <li><a class="text-theme-heading-color hocus:text-theme-link-hocus-color text-lg/tight will-change-transform" href="/onestop">OneStop</a></li>
                                 </ul>
                              </nav>
                           </div>
                           <div class="border-t-5 border-dotted border-white pt-8 lg:border-t-0 lg:pt-0 lg:border-r-5 lg:pr-12 lg:grow lg:[details_&amp;]:border-r-0 lg:[details_&amp;]:pr-0 lg:[details_&amp;]:border-t-5 lg:[details_&amp;]:pt-12">
                              <nav aria-label="Quick Links" class="">
                                 <ul role="list" class="columns-[calc(160rem/16)] gap-6 descendants:break-inside-avoid children:pb-4 -mb-4 leading-none lg:columns-2xs">
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Academic Calendar</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">A–Z Directory</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Blackboard</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Calendar of Events</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Office Hours</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Policies and Procedures</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Schedule of Courses</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Shocker Store</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Student Webmail</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Technology HelpDesk</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">Transfer to WSU</a></li>
                                    <li><a class="font-medium text-theme-heading-color hocus:text-theme-link-hocus-color text-base/tight lg:text-xl/tight will-change-transform" href="#">University Libraries</a></li>
                                 </ul>
                              </nav>
                           </div>
                        </div>
                        <div class="tw-hidden lg:block mx-auto lg:[details_&amp;]:tw-hidden"><img width="677" height="564" alt="" src="/_resources/_theme/images/wushock.svg"></div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</header><!--OU Search Ignore End Here-->
